### ISSUE TITLE
x86 syscall instructions mis-identified

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#104]
### Description

While using angrop on x86, a syscall gadget containing the x86_64 syscall instruction was identified for use in an example rop chain. This the x86_64 syscall instruction is not valid on x86, execution caused a SIGILL signal.

### Steps to reproduce the bug

Attached is a zip file. Unzip and run start.sh. This will init a python env, install requirements, build the test binary, and run the python test file. This file will provide an example of the issue.
[angrop_issue_x86_syscall.zip](https://github.com/angr/angrop/files/15123880/angrop_issue_x86_syscall.zip)

**Comment by Kyle-Kyle** [comment]
So it is not a vex or angr problem. But to make ROP chains generated by angrop more portable, the best solution may be filtering out the instruction in an ad-hoc manner

**Comment by Kyle-Kyle** [comment]
I made a mistake and pushed it to the master branch. But anyway, it should be fixed in https://github.com/angr/angrop/commit/8c7d117f4b9fd194ac9ecf8566ea4c05a652c002
