### ISSUE TITLE
SP not recognized as register on aarch64

### ISSUE THREAD

**Issue by crowell** [angr/angrop#11]
```
----> 1 rop.set_regs(sp = 0x10)

/home/jeff/.virtualenvs/angr/local/lib/python2.7/site-packages/angrop/chain_builder.pyc in set_regs(self, modifiable_memory_range, use_partial_controllers, rebase_regs, **registers)
     81
     82         gadgets, best_stack_change, _ = self._find_reg_setting_gadgets(modifiable_memory_range,
---> 83                                                                        use_partial_controllers, **registers)
     84         if gadgets is None:
     85             raise RopException("Couldn't set registers :(")

/home/jeff/.virtualenvs/angr/local/lib/python2.7/site-packages/angrop/chain_builder.pyc in _find_reg_setting_gadgets(self, modifiable_memory_range, use_partial_controllers, max_stack_change, **registers)
    853             search_regs.add(reg)
    854             if reg not in self._reg_list:
--> 855                 raise RopException("Register %s not in reg list" % reg)
    856
    857         # lets try doing a graph search to set registers, something like dijkstra's for minimum length

RopException: Register sp not in reg list
```

**Comment by TheCrazyT** [comment]
I guess the same happens on x86, using "rop.set_regs(esp=" just says "Register esp not in reg list"

**Comment by rhelmot** [comment]
since the stack pointer is kind of significant for ROP you will not be able to set it in this way (good job finding the relevant code). There is logic for doing stack pivots in angrop, which is kind of what you want, but I can't seem to find how to leverage that either intentionally or implicitly. I found the comment `Pivots are not really used by angrop right now` but that might be outdated? There's a lot of logic for throwing them around but idk how to apply them.

**Comment by TheCrazyT** [comment]
Another problem i notice is the following:
If you only want to change the stack pointer to initialize a rop chain you could also print all gadgets.
You will see a lot of gadgets with "Stack change" and bp register (normally should be ebp in my case, might be a bug).
But you won't find "Stack change: ebp" for example, although there exists "leave" or "mov esp,ebp" instructions.

I understand the fact that changing the stack pointer will destroy the rop-chain, but getting an initial location for changing the stackpointer might also be helpful (but thats probably a different story).
There are probably rare cases where you want to create something like rop-chain-loops i guess.
