### ISSUE TITLE
angrop fails as `xor` argument get lost in space

### ISSUE THREAD

**Issue by tux-mind** [angr/angrop#23]
### Symptoms 
I cannot run angrop on garbagetruck plaidctf chall due to an angr bug.

### Cause
It seems that Angr (it's vex engine ) cannot handle a Left Shift as 2nd operand of the `xor` ( or that operation shall be first moved to another reg ).

### Versions:
Angrop from sources, commit ce5d98b8f2f521a8e49e57f15f0ca4543c69c810
angr-7.7.12.16 from pip

### Binary: 
http://ropshell.com/ropsearch?h=67352acee5f5e8770121b9ea717b1c1a

### Script:
```python
import angr, angrop

p = angr.Project("garbagetruck")
rop = p.analyses.ROP()
rop.find_gadgets()

# ... never reached
```

### Debugging info:
https://pastebin.com/TbZBPpu7

**Comment by rhelmot** [comment]
I couldn't reproduce this. `find_gadgets()` finished successfully for me.
