### ISSUE TITLE
angr-bot dead on this repo

### ISSUE THREAD

**Issue by mahaloz** [angr/angrop#54]
### Description

angr-bot seems to have missed this repo since around September. The current version is `9.2.8` in this repo:
https://github.com/angr/angrop/blob/9284ce92d617ae8e9728a8e304c5b91967fbabd1/angrop/__init__.py#L1

On PyPi we are on `9.2.7` (last updated in September of 2022):
https://pypi.org/project/angrop/

As you might guess, this causes angrop to fail on import in any pypi install. 
@Kyle-Kyle did you intentionally remove it from PyPi? If not, @twizmwazin can this get readded?

**Comment by twizmwazin** [comment]
The bot didn't fail, we decided last year than angrop wouldn't be a tier 1 project regularly released to pypi. Since there was a breaking change, we can do a 1-time release.

**Comment by mahaloz** [comment]
I see. @twizmwazin would it be beneficial to add a `push to pypi on tag` action there, then? So it can at least be updated with new manually specified tags.

**Comment by twizmwazin** [comment]
That sounds like a great idea. Let's also set a lower bound on the angr dependency.

**Comment by twizmwazin** [comment]
I've added a release pipeline and released 9.2.8.
