### ISSUE TITLE
Bad Assumption About Rebasing Data Bytes in Chains against Binaries With PIE

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#67]
### Description

I found a bad assumption [here.](https://github.com/angr/angrop/blob/b06e817ddae59a7e7b693ecf5b1be51652831bba/angrop/chain_builder/mem_writer.py#L383)

It assumes if a binary is built against a binary with PIE enabled, than all concrete values need to be rebased. However, this is only true for gadgets, not data. Take the example where the user wants to build the following chain:

```
chain = rop.write_to_mem(0xdeadbeef, b"/bin/sh\x00")
```
This chain should write "/bin/sh" to the static memory location 0xdeadbeef. This location is not in program memory, and as such should not be rebased. 

The attached example will produce some chains that hit this bad logic, and some that do not. You will notice that the working chains (that avoid this logic) do not include 0xbeadbeef as a value exactly, but rather something very close to it. This is because, in these cases, angrop as picked a gadget that can not write directly to the address that a register points to, but rather adds or subtracts some small value from the value in the register, and uses the modified value as the write location. In these cases, angrop has not yet set a static concrete value when this logic is checked, and rather has a symbolic BV object in this location. Since it is not an int, this bad logic is bypassed.

Because of this behavior, one possible solution would be to allow the user to specify that a write location is static, and have angrop set it as a symbolic state BV even if it is not necessary for other analysis. 

### Steps to reproduce the bug

Included is a zip file. Extract the zip file and run start.sh. It will set up a python venv, install requirements, and run the test.py script. This python script will fetch the Ubuntu i386 libc and produce an example of a good chain (one that does not hit this code path) and a bad chain (one that does hit this code path).
[angrop_issue_67.zip](https://github.com/angr/angrop/files/14071208/angrop_issue_67.zip)

### Environment

Run on Ubuntu 22.04 in python 3.10

**Comment by Kyle-Kyle** [comment]
close as fixed in https://github.com/angr/angrop/pull/70

**Comment by Kyle-Kyle** [comment]
the testcase is included into CI btw.
Thank you so much for the contribution!
