### ISSUE TITLE
write_to_mem Broken for 32 bit Binaries

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#68]
### Description

As of [this commit](https://github.com/angr/angrop/commit/e4bc0c1496929f7d89242513078d943d7b72a8fa) rop.write_to_mem does not work properly for 32 bit binaries. The target write address will never appear in the chain. This problem does not effect 64 bit binaries. 

### Steps to reproduce the bug

Included is a zip file. Extract the zip file and run start_new.sh and start_old.sh (not at the same time). These will set up a python venv and install requirements. start_new will use the current git main of angrop, while start_old will use 9.2.8. Both will run a respective python script that will fetch the Ubuntu i386 libc and Ubuntu amd64 libc. Then it will produce example chains with both. The examples produced by 9.2.8 will be valid for both 32 and 64 bit version, while the examples produced by git main will only be valid for the 64 bit version.
[angrop_issue_68.zip](https://github.com/angr/angrop/files/14071223/angrop_issue_68.zip)

### Environment

Run on Ubuntu 22.04 in python 3.10

**Comment by Kyle-Kyle** [comment]
The former is added to my TODO list.
The latter is implemented here: https://github.com/angr/angrop/commit/1066f5a8c09757087b569ea4f7bf1dd7f81b9c92#diff-46ab7e747c5b3c59532f25b2c6b75fb806e8fbd260bc2147e6fc5bad37956ffcR404

**Comment by Kyle-Kyle** [comment]
notice that now users can specify whether to rebase a value like this:
```
    value = RopValue(0x800000, proj)
    value.rebase_ptr()
    chain = rop.write_to_mem(value, b"/bin/sh\x00")
    assert sum([not x._rebase for x in chain._values]) == 2 # 2 values
```

**Comment by Kyle-Kyle** [comment]
And the case in your uploaded files is included in our CI: https://github.com/angr/angrop/commit/1066f5a8c09757087b569ea4f7bf1dd7f81b9c92#diff-add18372f722092ba56ec70ef9cd474a14e028d17b2ee6b84e01e86fb3971783R71

**Comment by Kyle-Kyle** [comment]
will merge the commit once it passes all the CI tests
