### ISSUE TITLE
add_to_mem fails in main due to RopValue Type Error

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#73]
### Description

A recent change to the RopValue object seems to have broken the rop.add_to_mem() function.

### Steps to reproduce the bug

Included is a zip file. Extract the zip file and run start_new.sh. This will set up a python venv and install requirements. start_new will use the current git main of angrop. It will run a python script that will fetch the Ubuntu i386 libc and Ubuntu armel libc. Then it will prompt the user to produce example add_to_mem chains with both. 

The i386 one will error as follows:
```
"TypeError: bad operand type for unary ~: 'RopValue'" . 
```

The armel chain will error before it gets that far, as follows: 
```
"angrop.errors.RopException: Couldnt set registers for any memory add gadget". 
```
The armel error is shown further in #74.

[angrop_issue_73.zip](https://github.com/angr/angrop/files/14150064/angrop_issue_73.zip)

**Comment by Kyle-Kyle** [comment]
The root cause is that we didn't have a test case for `add_to_mem` in CI and somehow I missed the type casting from user input to RopValue in `add_to_mem`. Now it is fixed and the test case is integrated into CI. thanks!

**Comment by Kyle-Kyle** [comment]
btw, the fix commit is: https://github.com/angr/angrop/pull/75/commits/17bd2e11f80376fc3a0bec9231981db5d523aa0b
