### ISSUE TITLE
Fails to craft difficult chain

### ISSUE THREAD

**Issue by CptGibbon** [angr/angrop#8]
Current build fails to craft a write_to_mem() chain for a binary with some odd gadgets (specifically the "fluff" challenge at ropemporium.com)
A working chain may be crafted using gadgets found with the 'ropper' tool.

**Comment by salls** [comment]
Okay so I looked at it briefly. This is the gadget that needs to be used:
```
0x40082e
mov    QWORD PTR [r10],r11
pop    r13
pop    r12
xor    BYTE PTR [r10],r12b
ret    
```

To fix this angrop needs handle multiple memory writes/changes in the same gadget. One solution might be to collapse them into a single memory write when they have the same address. Should be fixable when I get a bit of free time. 

[fluff.zip](https://github.com/salls/angrop/files/752704/fluff.zip)
