### ISSUE TITLE
Long Chains Timeout when calling chain.payload_str()

### ISSUE THREAD

**Issue by astewart-bah** [angr/angrop#87]
### Description

I have run into an issue with long rop chains where calling chain.payload_str() receives a timeout.
```
[angrop] Timeout
```

This is due to the hard coded timeout [here](https://github.com/angr/angrop/blob/ba57c26994b8e0818ccc2b7efa141dba69954956/angrop/rop_chain.py#L61) for _concretize_chain_values
Likely do to the fact that the timeout is independent of the number of ._values that need to be processed. 

### Steps to reproduce the bug

Attached is a zip file containing an example script. Run setup.sh to build the .venv and run the example.

This will build an example chain and call chain.payload_str() in a loop where the chain size is increased until the timeout is reached. 
[angrop_issue.zip](https://github.com/angr/angrop/files/14465513/angrop_issue.zip)

**Comment by Kyle-Kyle** [comment]
a proposed patch is pending for merge: https://github.com/angr/angrop/pull/88

**Comment by Kyle-Kyle** [comment]
with this patch, you will be able to set the default timeout for all chains, or set a special timeout for individual chains
