### ISSUE TITLE
gets stuck while generating memory write chain

### ISSUE THREAD

**Issue by rhelmot** [angr/angrop#92]
### Description

Running rex hangs in z3 while using angrop. Strangely, the constraints that it hangs on are trivially false, and plugging them into a fresh solver is able to solve them immediately. This is probably either a claripy or z3 bug, but I can't reproduce it elsewhere so I'm putting it here for now.

### Steps to reproduce the bug

I don't think I can distribute the files publically. Contact me and ask for dandelion:lunchables/mypipeline/samples/1.tar.gz and dandelion:lunchables/mypipeline/crashes/502392183509221377.bin.

### Environment

angr environment report
=============================
Date: 2024-03-25 22:21:49.619203
Running in virtual environment at /home/audrey/.virtualenvs/angr-c
/home/audrey/proj/angr/angr/angr/misc/bug_report.py:88: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources  # pylint:disable=import-outside-toplevel
Platform: linux-x86_64
Python version: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
######## angr #########
Python found it in /home/audrey/proj/angr/angr/angr/__init__.py
Pip version angr 9.2.89.dev0
Git info:
        Current commit 45cb17dfd014978248fb7e2900c9707910b5eae1 from branch master
        Checked out from remote origin: git@github.com:angr/angr.git
######## ailment #########
Python found it in /home/audrey/proj/angr/ailment/ailment/__init__.py
Pip version ailment 9.2.89.dev0
Git info:
        Current commit c27c069586d147fc21daf664114df8e85df86adb from branch master
        Checked out from remote origin: https://github.com/angr/ailment.git
######## cle #########
Python found it in /home/audrey/proj/angr/cle/cle/__init__.py
Pip version cle 9.2.89.dev0
Git info:
        Current commit 2671c1efa743ebe52da8d106ad52336ba4f7485b from branch master
        Checked out from remote origin: https://github.com/angr/cle.git
######## pyvex #########
Python found it in /home/audrey/proj/angr/pyvex/pyvex/__init__.py
Pip version pyvex 9.2.89.dev0
Git info:
        Current commit 1b93db3d7a1f95c64f57fc036794d71d1c9b3167 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex.git
######## claripy #########
Python found it in /home/audrey/proj/angr/claripy/claripy/__init__.py
Pip version claripy 9.2.89.dev0
Git info:
        Current commit 06a9bd3f7eec4a1ffc77c8676b29ae79b4630796 from branch master
        Checked out from remote origin: git@github.com:angr/claripy.git
######## archinfo #########
Python found it in /home/audrey/proj/angr/archinfo/archinfo/__init__.py
Pip version archinfo 9.2.89.dev0
Git info:
        Current commit eebcd9118c02cc7abd24681686d09ab394a937bf from branch master
        Checked out from remote origin: https://github.com/angr/archinfo.git
######## z3 #########
Python found it in /home/audrey/.virtualenvs/angr-c/lib/python3.11/site-packages/z3/__init__.py
Pip version z3-solver 4.10.2.0
Couldn't find git info
######## unicorn #########
Python found it in /home/audrey/.virtualenvs/angr-c/lib/python3.11/site-packages/unicorn/__init__.py
Pip version unicorn 2.0.1.post1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/audrey/proj/angr/angr/angr/state_plugins/../lib/angr_native.so', handle 2c0c430 at 0x7cb326d27190>
unicorn: <CDLL '/home/audrey/.virtualenvs/angr-c/lib/python3.11/site-packages/unicorn/lib/libunicorn.so.2', handle 26116c0 at 0x7cb32a813490>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7cb32b6f41d0>
z3: <CDLL '/home/audrey/.virtualenvs/angr-c/lib/python3.11/site-packages/z3/lib/libz3.so', handle 22552d0 at 0x7cb32d39ec10>

**Comment by Kyle-Kyle** [comment]
should be fixed by https://github.com/angr/angrop/commit/88056735f06a100b4cbcae03664420be2d6d77d5
